### ISSUE TITLE
Вопросы по планшетной версии

### ISSUE THREAD

**Issue by JennyBambu** [jokerinteractive/ledwit.ru#15]
1) Не получилось экспортировать черный геометрический участок фона, ограничивающий главное изображение, я пробовала и в фотошопе и в фигме, не вышло:( Получается экспортировать только обрезанное изображение, вместо того чтобы получить черную фигуру отдельно, чтобы можно было положить ее сверху на расширяющуюся фоновую картинку
Как правильно это сделать?

2) Могу ли я экспериментировать с блоками на примере блока services__guarantee , в котором часть взята из расширения планшетного, а часть с мобильного? Исходила из того, что этот и последующие блоки нарисованы на 786px и некрасиво ложатся на меньшую ширину.

Я хотела эти блоки полностью по макету сделать с 768px, а с 500 до 768 сделать компромиссный вариант, что скажете?
3)Можно ли взять свг-фигуры соц.сетей из Седоны/Кэт Энерджи? Большая часть там есть в формате svg, а внешне очень похожи/такие же

4)Чтобы фон от блока about заходил под header нужно перенести фоновую картинку из about в body и позиционировать? Или сделать header абсолютно позиционированным? Какой вариант лучше?

**Comment by ademaro** [comment]
1) оставляем так пока, центрируем, оставим когда десктоп будет
2) да, экспериментируем — с фокусом на результат, что бы показать что есть, мелочи будем ровнять уже по ходу
3) да, добро!
4) думаю, как проще и быстрее, особо без разницы
