### ISSUE TITLE
PP некорректно отображается

### ISSUE THREAD

**Issue by JennyBambu** [jokerinteractive/ledwit.ru#19]
Планшетная версия pp вместо с 768px отображаться начинает с 834px, если это легко и быстро правится, то было бы здорово исправить, если нет - то я в принципе приноровилась под нее подстраиваться)

**Comment by ademaro** [comment]
правится быстро и легко, в этом файле: https://github.com/jokerinteractive/ledwit.ru/blob/master/src/views/layout.j2

**Comment by JennyBambu** [comment]
Упс, да, быстро....
