### ISSUE TITLE
Как использовать тег picture c учетом шаблонов?

### ISSUE THREAD

**Issue by JennyBambu** [jokerinteractive/ledwit.ru#21]
Не получилось расширить шаблоны  img до picture, как правильно их нужно написать, чтобы была возможность использовать <picture> ?

Я пробовала разные варианты, либо все картинки использовали ссылку для первой картинки, либо все ломалось целиком.

**Comment by ademaro** [comment]
вообще есть мискин https://github.com/jokerinteractive/ledwit.ru/blob/master/src/views/common/mixins/picture.pug
надо его пересмотреть

а что именно не работает? пришли ссылку на codepen, посмотрим

**Comment by JennyBambu** [comment]
Хм, я не совсем поняла, как в https://codepen.io/pen/ тут можно создать демонстрацию проблемы с использованием шаблонов...
Я создала пулреквест из отдельной ветки для этого, сможете посмотреть?
https://github.com/jokerinteractive/ledwit.ru/pull/22

Проблема в том, что при добавлении тега  `<picture>`, ширина, заданная для класса тега `<img>` (`results__gallery-image`) = (30%), начинает некорректно отображаться (скрины приложила), занимая не 30% от всей обертки `results__gallery`,как было запланировано, а 30% от другой обертки меньшего размера
1 скрин -  как стало
2 скрин -  как было до добавления `<picture>`

![with-picture](https://user-images.githubusercontent.com/70893238/120256981-fb7c2700-c297-11eb-9df3-3e2875eb81ec.jpg)
![Screenshot_219](https://user-images.githubusercontent.com/70893238/120256983-fc14bd80-c297-11eb-9746-acb769475f41.jpg)
![Screenshot_218](https://user-images.githubusercontent.com/70893238/120256985-fcad5400-c297-11eb-9a45-b0fe5513b9e1.jpg)
![Screenshot_217](https://user-images.githubusercontent.com/70893238/120256988-fcad5400-c297-11eb-8a9f-f34f3f434e7a.jpg)

**Comment by ademaro** [comment]
у `results__gallery-image` — надо убрать `width: 30%` и всё встанет норм:
![Uploading Screenshot 2021-06-01 at 15.14.34.png…]()

**Comment by ademaro** [comment]
<img width="941" alt="Screenshot 2021-06-01 at 15 14 34" src="https://user-images.githubusercontent.com/416356/120330038-b7674180-c2ec-11eb-85cb-cc4918c53b99.png">
