### ISSUE TITLE
Проблема со шрифтом

### ISSUE THREAD

**Issue by JennyBambu** [jokerinteractive/ledwit.ru#25]
На десктопных разрешениях размер шрифта, несмотря на заданный размер (либо конкретно, либо inherit) отображается большего размера, весь ПП начинает ехать соответственно, но если поменять зум в любую сторону, то все становится как нужно: размер шрифта становится таким, как и ожидалось. (прилагаю скриншот)
![Screenshot_225](https://user-images.githubusercontent.com/70893238/121827589-47ca5c80-ccc5-11eb-99ae-a6d5b6f7c8ab.jpg)С чем это может быть связано? 

P.S. Смотрю, как работает - в Google

**Comment by ademaro** [comment]
Раньше было замечено у FF, будем смотреть) думаю, пока не очень принципиально, пока закрою
