### ISSUE TITLE
Подправить ширины в адаптиве после изменений

### ISSUE THREAD

**Issue by ademaro** [jokerinteractive/ledwit.ru#28]
@JennyBambu 
Сделал замену на новый синтаксис адаптива, посмотри, пожалуйста, думаю, у тебя быстрее получится подправить

**Comment by JennyBambu** [comment]
Здравствуйте,

Возникает такая ошибка, как ее можно исправить?
![Screenshot_235](https://user-images.githubusercontent.com/70893238/123559312-e82f7f00-d7a3-11eb-99d7-5de4aa8a4cf1.jpg)

Не совсем поняла, как нужно быть с изменениями, которые вы внесли. Например, вы убрали мои ширины и заменили их другими (скриншот), подстраивать все под новые значения или это было для примера и могу вернуть старые значения ширин?
![Screenshot_238](https://user-images.githubusercontent.com/70893238/123559386-7146b600-d7a4-11eb-8cc3-6345d6a8d2e7.jpg)

Или например, добавили, что ширина должна быть 90%, это нужно оставить?
![Screenshot_237](https://user-images.githubusercontent.com/70893238/123559415-96d3bf80-d7a4-11eb-8465-dc7ebec3a579.jpg)

**Comment by JennyBambu** [comment]
Удалила папку node_modules, набрала npm i, но во время дальнейшей сборки/запуска возникает ошибка
![Screenshot_241](https://user-images.githubusercontent.com/70893238/123647342-ac8ec680-d830-11eb-903e-b9c2c448062c.jpg)

**Comment by ademaro** [comment]
@JennyBambu это в какой ветке? Это после удаления папки node_modules и после `npm i`?

**Comment by ademaro** [comment]
https://github.com/jokerinteractive/ledwit.ru/blob/master/gulpfile.babel.js — gulp-sass вообще нет такого в последнем коммите

**Comment by JennyBambu** [comment]
> @JennyBambu это в какой ветке? Это после удаления папки node_modules и после `npm i`?

В developer, где я все делала до этого

"Это после удаления папки node_modules и после `npm i`" - да

**Comment by JennyBambu** [comment]
> https://github.com/jokerinteractive/ledwit.ru/blob/master/gulpfile.babel.js — gulp-sass вообще нет такого в последнем коммите

![Screenshot_242](https://user-images.githubusercontent.com/70893238/123668368-b4a43180-d843-11eb-820b-06cb10b855a0.jpg)

Скопировала вручную, странно что когда делала git pull orgin developer, не все видимо, пришло...

**Comment by JennyBambu** [comment]
Теперь сборка  пошла, но вот с такой ошибкой: 
![Screenshot_243](https://user-images.githubusercontent.com/70893238/123668648-faf99080-d843-11eb-9475-e652e5c2c562.jpg)

**Comment by ademaro** [comment]
вручную не нужно, могут возникнуть конфликты слияния

**Comment by ademaro** [comment]
Забери из мастера всё, плиз

**Comment by JennyBambu** [comment]
В мастере сделать git pull?
А в developer : git merge master?

**Comment by ademaro** [comment]
Я обновил developer, можно сразу оттуда
