### ISSUE TITLE
Доделать мобильную версию

### ISSUE THREAD

**Issue by ademaro** [jokerinteractive/ledwit.ru#6]
- [ ] блоки на всю ширину (имелось в виду, что фон тянем, контейнеры — такое себе тянуть))
- [x] сделать нормальную обрезку изображений (заодно добавить @2x)
- [x] попробовать резину (но не обязательно)

Все поправки в #5

**Comment by ademaro** [comment]
Про блоки на всю ширину на мобильной версии — я говорил про фон, который не тянулся, а фиксировался на 320 по ширине. Может, запутал резину, но её можно делать для контента, но, например, с 320 до 380px, дальше фиксировать. Что бы получилось что-то вроде этого:
![](https://i.imgur.com/M9Ol05W.png)
красные стрелки — тянем по всей ширине фон, зелёные — фиксируем контент, что бы не расползался.
вместо такого, что сейчас:
![](https://i.imgur.com/VslOyot.png)
Есть разница для тебя?

**Comment by JennyBambu** [comment]
Да, разница есть!)
Я искренне заблуждалась, что топовая резина - это вот как сейчас, когда все тянется максимально)))
Переделаю)
