### ISSUE TITLE
Поправить ПП на мобиле

### ISSUE THREAD

**Issue by ademaro** [jokerinteractive/ledwit.ru#7]
Поплыло всё...
https://i.imgur.com/mxIGTQY.png

Предлагаю сразу поправить...

**Comment by ademaro** [comment]
Опять же, можем обсудить — надо ли сейчас? Просто мне кажется, что можно поправить минут за 20 всё, но это не факт) 

@JennyBambu У тебя показывается вообще панель с PixelGlass (наложение картинки по кнопке "on")?

**Comment by JennyBambu** [comment]
Да, показывает) 
ок)
