### ISSUE TITLE
Запустить линтер

### ISSUE THREAD

**Issue by ademaro** [jokerinteractive/ledwit.ru#8]
`npm run test` сам много поправит, остальное — доправить

ну и можно поставить плагин `stylelint` для редактора, будет сразу подсвечивать, удобно

**Comment by ademaro** [comment]
@JennyBambu, с этим всё понятно?) Можно реакции ставить, например: 👀  =)

**Comment by JennyBambu** [comment]
![Screenshot_183](https://user-images.githubusercontent.com/70893238/117300203-018e0c00-ae82-11eb-8f99-d3aa2148cf66.jpg)

поняла про issues, буду сюда писать)
на другой консоли то же самое, я git bash установила дополнительно, powerShell не видит команды git

**Comment by ademaro** [comment]
Попробуй в package.json поменять строчку на такую:
`    "test": "stylelint \"src/sass/**/*.scss\" --config .stylelintrc.json --fix"`
вместо
`    "test": "stylelint 'src/sass/**/*.scss' --config .stylelintrc.json --fix"`

**Comment by JennyBambu** [comment]
> "test": "stylelint \"src/sass/**/*.scss\" --config .stylelintrc.json --fix"

Да, получилось=)
